assert

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -71,16 +71,27 @@ jobs:
           kubectl -n k8skafka-system wait kafkatopic/test-create-new --for=condition=Ready --timeout=5m
           res=$(kubectl -n kafka exec -it kafka-client -- kafka-topics --describe --topic test-create-new --bootstrap-server kafka-cp-kafka:9092)
           [[ -z "$res" ]] && (there is no topic test-create-new && exit 1) || echo "topic test-create-new successfully created"
+
           echo "test adding new partitions"
           kubectl -n k8skafka-system apply -f ./config/testdata/kafkatopics/add-partitions
           sleep 2
-          i=1; while [ $i -le 5 ]; do \
+          expectedPartitions=20; e=true; i=1; while [ $i -le 5 ]; do \
           res=$(kubectl -n kafka exec -it kafka-client -- kafka-topics --describe --topic test-create-new --bootstrap-server kafka-cp-kafka:9092); \
-          res=$(echo $res | wc -l | xargs);
-          [[ $res == 21 ]] && \
-          (echo "topic has expected number of partitions: 21" && i=6 ) || \
-          (echo "expected 21 partitions, got $res" && let "i+=1"; sleep 3); \
+          res=$(echo $res | tail -n+2 | wc -l | xargs); \
+          if [[ $res == $expectedPartitions ]]; then \
+          echo "topic has expected number of partitions: $expectedPartitions"; \
+          e=false; \
+          break; \
+          else \
+          echo "expected $expectedPartitions partitions, got $res"; \
+          let "i+=1"; \
+          sleep 3; \
+          fi; \
           done
+          if [[ $e == true ]]; then \
+          echo "failed to get required number of partitions in time"; \
+          exit 1; \
+          fi
       - name: Logs
         run: |
           kubectl -n k8skafka-system wait --for=condition=ready pod -l app=k8skafka-controller && kubectl -n k8skafka-system logs deploy/k8skafka-controller
